### ISSUE TITLE
Ajouter la possibilité de vérifier les country names

### ISSUE THREAD

**Issue by jeremyfix** [dataforgoodfr/12_taxobservatory#37]
Lors de l'étape d'extraction des tables, l'OCR peut se tromper sur le parsing des noms de pays; On dispose de la liste des noms de pays dans `country_by_country/utils/constants.py` et on peut éventuellement corriger les erreurs de l'OCR avec ces propositions de pays existants.

**Comment by RonanMorgan** [comment]
je pensais utiliser la distance de Levenshtein pour pouvoir associer chaque nom de pays "detecté" à son nom le plus proche dans la liste hardcodé.
Par contre comment traiter les cas d'erreur suite à l'application de la distance ? ou juste se dire qu'on pourra de toute façon faire une modification manuelle dans Clean_Table ?

**Comment by RonanMorgan** [comment]
blocked by https://github.com/dataforgoodfr/12_taxobservatory/pull/48

**Comment by jeremyfix** [comment]
solved by PR #55

**Comment by RonanMorgan** [comment]
ici : https://github.com/dataforgoodfr/12_taxobservatory/pull/56
