### ISSUE TITLE
Page Tables : appliquer un "form" sur le tableau carrément pour éviter le blanc

### ISSUE THREAD

**Issue by jeremyfix** [dataforgoodfr/12_taxobservatory#39]

**Comment by RonanMorgan** [comment]
le fait d'utiliser un container de type form implique que streamlit ne va pas rerun à chaque fois qu'on modifie un widget. Par exemple :
with form: 
    widget1(blablabla)
    widget2(blablabla)
  
  C'est très pratique si on veut modifier plusieurs fois une widgets (ou plusieurs widget différentes) avant de valider le passage à une autre step (par exemple dans Selected_Pages j'ai mis un forme sur la widget selectbox qui permet de selectionner plusieurs pages qui vont ensuite être envoyer à l'algo d'extraction, ça évite de perdre une seconde à chaque fois que l'on ajoute / supprime une page de la selection) 
  
  Quand j'ai créé cette tâche le fonctionnemenent de la page Clean_Tables était très complexe avec deux tableaux synchronisé entre eux et streamlit était tout le temps en train de faire de rerun(), il me semble que ce n'est plus le cas maintenant, à voir à la toute fin du projet si on à ce genre de problèmes.
