### ISSUE TITLE
Page Headers : donner la possibilité de choisir quel headers on garde 

### ISSUE THREAD

**Issue by jeremyfix** [dataforgoodfr/12_taxobservatory#40]
(pour l'instant que les headers de la première table)

**Comment by RonanMorgan** [comment]
C'est pour la nouvelle page de merge : si vous prenez le fichier AXA , unstructured détecte 5 tables différentes qu'il faut merger et bien sûr les headers ne se ressemble pas j'ai donc pris par défaut d'utiliser le header de la première table détectée et de l'utiliser pour chaque table pourtant si on regarde tout les headers ils sont mieux detectés dans les autres tables (mais pas parfait non plus)
Est ce que ça vaut le coup de choisir les headers que l'on veut appliquer aux autres ? en pratique je ne suis pas sûr car aucun n'est parfait donc dans tout les cas il y aura une opération manuel à faire.

**Comment by RonanMorgan** [comment]
useless according to Kane's comment
