### ISSUE TITLE
file name : utiliser le nouveau widget st_pages pour hardcoder le nom des pages et ne plus utiliser le nom des fichiers

### ISSUE THREAD

**Issue by jeremyfix** [dataforgoodfr/12_taxobservatory#43]

**Comment by RonanMorgan** [comment]
A l'heure actuelle le nom des onglets est forcément égal aux noms des fichiers pythons. C'est pas génial et il existe une nouvelle méthode pour changer ça : apparemment ce serait un widget qui s'appelle st_pages.
