### ISSUE TITLE
Collecte - google searches get stuck after 10/15 searches

### ISSUE THREAD

**Issue by giuali** [dataforgoodfr/12_taxobservatory#50]
Je suis dans **main/collecte** et j'utilise **pdf_downloader.py** pour les companies_names j'utilise  "collecte/data/company_names.csv "
issue 1: les recherches s'arrêtent après 10/15 recherches
![Screenshot 2024-04-08 at 17 20 46](https://github.com/dataforgoodfr/12_taxobservatory/assets/103266974/72bd20b4-8215-4ef1-bf33-550702c6dee5)

**Comment by FS-CS** [comment]
Fixé dans https://github.com/dataforgoodfr/12_taxobservatory/commit/53682419e934d2ae790ae2c4be40db9ac6678f03

Téléchargements lents limités dans le temps par un mécanisme de timeout configurable.
