### ISSUE TITLE
Gérer le cas des tableaux transposés

### ISSUE THREAD

**Issue by RonanMorgan** [dataforgoodfr/12_taxobservatory#54]
![image](https://github.com/dataforgoodfr/12_taxobservatory/assets/49660557/c8da6e50-6920-43d9-85a1-f5b2aa2ecbf9)

**Comment by jeremyfix** [comment]
J'ai ajouté une petite checkbox dans la branche `issue_54` ; @RonanMorgan : tu te souviens du PDF utilisé pour l'illustration de l'issue que je vois ce que ça donne ?

**Comment by RonanMorgan** [comment]
Enel 2020
